export const defaultFormValues = {
  id: '',
  number: '',
  recipient: {
    companyName: '',
    city: '',
    street: '',
    postalCode: '',
    nip: '',
    phone: '',
    mail: '',
    bankAccount: '',
  },
  sender: {
    companyName: '',
    city: '',
    street: '',
    postalCode: '',
    nip: '',
    phone: '',
    mail: '',
    bankAccount: '',
  },
  items: [],
};
