export const INVOICE_USER_FIELDS = [
  {
    label: 'invoice.form.companyName',
    valid: true,
    value: '',
    key: 'companyName',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.city',
    value: '',
    valid: true,
    key: 'city',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.street',
    value: '',
    valid: true,
    key: 'street',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.postCode',
    value: '',
    valid: true,
    key: 'postcode',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.nip',
    value: '',
    valid: true,
    type: 'number',
    key: 'nip',
    validationMessage: 'invoice.validations.fieldRequired',
  },
  {
    label: 'invoice.form.phone',
    value: '',
    valid: true,
    key: 'phone',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.email',
    value: '',
    valid: true,
    type: 'email',
    key: 'email',
    validationMessage: 'invoice.validations.fieldRequired',
  },
  {
    label: 'invoice.form.bankAccount',
    value: '',
    valid: true,
    key: 'bankAccount',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
];

export const INVOICE_ITEM_FIELDS = [
  {
    label: 'invoice.form.name',
    value: '',
    valid: true,
    key: 'name',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.amount',
    value: '',
    valid: true,
    type: 'number',
    key: 'amount',
    validationMessage: 'invoice.validations.fieldRequired',
  },
  {
    label: 'invoice.form.unit',
    value: '',
    valid: true,
    key: 'unit',
    validationMessage: 'invoice.validations.fieldRequired',
    type: 'text',
  },
  {
    label: 'invoice.form.tax',
    value: '',
    valid: true,
    type: 'number',
    key: 'tax',
    validationMessage: 'invoice.validations.fieldRequired',
  },
  {
    label: 'invoice.form.price',
    value: '',
    valid: true,
    type: 'number',
    key: 'price',
    validationMessage: 'invoice.validations.fieldRequired',
  },
];

export const INVOIEC_NUMBER_FIELD = {
  label: 'invoice.form.no',
  value: '',
  valid: true,
  key: 'number',
  validationMessage: 'invoice.validations.fieldRequired',
  type: 'text',
};
