export const INVOICE_USER_FIELDS = [
  {
    label: 'Company Name',
    valid: true,
    value: '',
    key: 'companyName',
    validationMessage: 'Company Name is required',
    type: 'text',
  },
  {
    label: 'City',
    value: '',
    valid: true,
    key: 'city',
    validationMessage: 'City is required',
    type: 'text',
  },
  {
    label: 'Street',
    value: '',
    valid: true,
    key: 'street',
    validationMessage: 'Street is required',
    type: 'text',
  },
  {
    label: 'Postcode',
    value: '',
    valid: true,
    key: 'postcode',
    validationMessage: 'Postcode is required',
    type: 'text',
  },
  {
    label: 'NIP',
    value: '',
    valid: true,
    type: 'number',
    key: 'nip',
    validationMessage: 'NIp is required',
  },
  {
    label: 'Tel',
    value: '',
    valid: true,
    key: 'phone',
    validationMessage: 'Tel is required',
    type: 'text',
  },
  {
    label: 'E-mail',
    value: '',
    valid: true,
    type: 'email',
    key: 'email',
    validationMessage: 'E-mail is required',
  },
  {
    label: 'Bank account',
    value: '',
    valid: true,
    key: 'bankAccount',
    validationMessage: 'Bank account is required',
    type: 'text',
  },
];

export const INVOICE_ITEM_FIELDS = [
  {
    label: 'name',
    value: '',
    valid: true,
    key: 'name',
    validationMessage: 'Name is required',
    type: 'text',
  },
  {
    label: 'amount',
    value: '',
    valid: true,
    type: 'number',
    key: 'amount',
    validationMessage: 'Amount is required',
  },
  {
    label: 'unit',
    value: '',
    valid: true,
    key: 'unit',
    validationMessage: 'Unit is required',
    type: 'text',
  },
  {
    label: 'tax',
    value: '',
    valid: true,
    type: 'number',
    key: 'number',
    validationMessage: 'Tax is required',
  },
  {
    label: 'price',
    value: '',
    valid: true,
    type: 'number',
    key: 'price',
    validationMessage: 'Price is required',
  },
];

export const INVOIEC_NUMBER_FIELD = {
  label: 'No.',
  value: '',
  valid: true,
  key: 'number',
  validationMessage: 'No. is required',
  type: 'text',
};
